In [2]:
import pandas as pd

In [3]:
import numpy as np
import sklearn

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
dataset = pd.read_csv("poker-hand-testing.data")

In [6]:
dataset.head()

S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  CLASS
0   1   1   1  13   2   4   2   3   1  12      0
1   3  12   3   2   3  11   4   5   2   5      1
2   1   9   4   6   1   4   3   2   3   9      1
3   1   4   3  13   2  13   2   1   3   6      1
4   3  10   2   7   1   2   2  11   4   9      0

In [7]:
dataset["CLASS"].value_counts()

0    501209
1    422498
2     47622
3     21121
4      3885
5      1996
6      1424
7       230
8        12
9         3
Name: CLASS, dtype: int64

In [8]:
x= dataset.iloc[:,0:10].values
x


array([[ 1,  1,  1, ...,  3,  1, 12],
       [ 3, 12,  3, ...,  5,  2,  5],
       [ 1,  9,  4, ...,  2,  3,  9],
       ...,
       [ 1, 11,  4, ..., 13,  2,  7],
       [ 3, 11,  1, ..., 13,  2,  8],
       [ 2,  5,  2, ...,  3,  3,  3]], dtype=int64)

In [13]:
y=dataset.iloc[:,10].values
list(y)
b=y.tolist()
bf=pd.DataFrame(b,columns=['Class'])

In [15]:
bf['Class'].value_counts()

0    501209
1    422498
2     47622
3     21121
4      3885
5      1996
6      1424
7       230
8        12
9         3
Name: Class, dtype: int64

In [ ]:
y=["0","1","2","3","4","5","7","8","9"]

In [42]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [43]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [44]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [45]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[87837 12322     1     0     0     0     0     0     0]
 [29767 54669   262    32    14     0     1     0     0]
 [  712  8316   451    22     0     0     6     0     0]
 [  210  3459    52   362     0     0     2     0     0]
 [  114   624     5     0    14     0     0     0     0]
 [  324    19     0     0     0    64     0     0     0]
 [    1   195    44    33     0     0     9     0     0]
 [    0    35     4    15     0     0     1     0     0]
 [    0     2     0     0     0     0     0     0     0]]
C:\Program Files\Python37\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
              precision    recall  f1-score   support

           0       0.74      0.88      0.80    100160
           1       0.69      0.65      0.67     84745
           2       0.55      0.05      0.09      9507
           3      